version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      swc:
        patterns:
          - "@swc/*"
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
      prettier:
        patterns:
          - "eslint-config-prettier"
          - "eslint-plugin-prettier"
          - "prettier"
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
