name: Checkout

on:
  workflow_call

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache/save@v3
      with:
        path: .
        key: cache-${{ github.ref_name }}
