name: Lint (ESLInt)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml
  install:
    needs: checkout
    uses: ./.github/workflows/install.yml
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - run: pnpm lint
