name: Lint (ESLInt)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    uses: ./.github/workflows/checkout.yml
  install:
    needs: checkout
    uses: ./.github/workflows/install.yml
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.27.0
    - uses: actions/cache/restore@v3
      with:
        path: .
        key: cache-${{ github.job }}-${{ github.ref_name }}
    - run: pnpm lint
