name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - name: Checkout repository code
      uses: actions/checkout@v3

    # install
    - name: Setup PNPM
      if: 
      uses: pnpm/action-setup@v2
      with:
        version: 7.27.0
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    # get latest version number
    - name: Install semver package
      run: pnpm add semver
    - name: Retrieve the latest release and current package versions
      id: get-releases
      uses: actions/github-script@v6
      with:
        script: |
          const script = require('./.github/workflows/scripts/release-get-releases.js')
          return await script({github, context})
    - name: Uninstall semver package 
      run: git restore . && pnpm install --frozen-lockfile

    # release to npm
    - name: Release to NPM
      if: ${{ fromJSON(steps.get-releases.outputs.result).latestIsNew }}
      run: pnpm release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}

    # tag release in github
    - name: Tag release in GitHub
      if: ${{ fromJSON(steps.get-releases.outputs.result).latestIsNew }}
      uses: actions/github-script@v6
      env:
        RELEASE_TAG_NAME: ${{ fromJSON(steps.get-releases.outputs.result).package }}
      with:
        result-encoding: string
        script: |
          const script = require('./.github/workflows/scripts/release-tag-release.js')
          await script({github, context})
